name: Deploy shagbot
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    name: Trigger Deploy Hook
    runs-on: ubuntu-latest
    environment: shajeshbot
    steps:
      - name: curl deploy hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
